# Form implementation generated from reading ui file 'termoline_ui.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Termoline(object):
    def setupUi(self, Termoline):
        Termoline.setObjectName("Termoline")
        Termoline.resize(800, 600)
        Termoline.setMinimumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(parent=Termoline)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.start_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.start_button.setMaximumSize(QtCore.QSize(75, 23))
        self.start_button.setObjectName("start_button")
        self.horizontalLayout.addWidget(self.start_button)
        self.stop_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.stop_button.setMaximumSize(QtCore.QSize(75, 23))
        self.stop_button.setObjectName("stop_button")
        self.horizontalLayout.addWidget(self.stop_button)
        self.line_edit_amount = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.line_edit_amount.setMaximumSize(QtCore.QSize(31, 23))
        self.line_edit_amount.setObjectName("line_edit_amount")
        self.horizontalLayout.addWidget(self.line_edit_amount)
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setMaximumSize(QtCore.QSize(85, 20))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.radio_cont = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radio_cont.setObjectName("radio_cont")
        self.horizontalLayout.addWidget(self.radio_cont)
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_4.setMaximumSize(QtCore.QSize(75, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.tableWidget = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout.addWidget(self.tableWidget)
        Termoline.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=Termoline)
        self.statusbar.setObjectName("statusbar")
        Termoline.setStatusBar(self.statusbar)

        self.retranslateUi(Termoline)
        QtCore.QMetaObject.connectSlotsByName(Termoline)

    def retranslateUi(self, Termoline):
        _translate = QtCore.QCoreApplication.translate
        Termoline.setWindowTitle(_translate("Termoline", "MainWindow"))
        self.start_button.setText(_translate("Termoline", "Старт"))
        self.stop_button.setText(_translate("Termoline", "Стоп"))
        self.label.setText(_translate("Termoline", "Кол-во отчетов"))
        self.radio_cont.setText(_translate("Termoline", "Непрерывно"))
        self.pushButton_4.setText(_translate("Termoline", "Сохранить"))
        self.label_2.setText(_translate("Termoline", "Данные с датчиков"))
